Add option to URL encode SVG
nuxt-community/svg-module pull request #20
Opened 2019-10-29 15:58 UTC by bravokiloecho

Use webpack's `svg-url-loader` to load SVGs as a utf-8 DataURL string. Useful when using SVGs in CSS.

2019-10-29 16:09 UTC, ricardogobbosouza approved these changes

2019-11-21 14:11 UTC, brhx requested changes
Please could you rebase this against master?

2019-11-25 09:47 UTC, bravokiloecho commented
Hey @sam3d, apologies for the delay! The PR branch should now be up to date :)

2020-01-28 11:45 UTC, bravokiloecho commented
Hi @sam3d  or @ricardogobbosouza, any chance on getting this merged? The conflicts were resolved..

Thanks!

2020-04-13 09:45 UTC, closed without merging