Add raw SVG loader
nuxt-community/svg-module pull request #21
Opened 2019-10-29 16:16 UTC by bravokiloecho

Add the ability to import SVG as raw data using webpack's `raw-loader`. Useful if you need to manipulate the SVG before adding it to the DOM.

2019-10-29 17:45 UTC, ricardogobbosouza requested changes

2019-10-29 17:45 UTC, ricardogobbosouza commented on README.md
> +
Remove extra blank line

2019-10-29 17:45 UTC, ricardogobbosouza commented on example/pages/index.vue
> +import nuxtLogoRaw from '~/assets/nuxt.svg?raw'
Use `PascalCase` -> `NuxtLogoRaw`

2019-10-30 17:28 UTC, bravokiloecho commented on README.md
> +
Done

2019-10-30 17:28 UTC, bravokiloecho commented on example/pages/index.vue
> +import nuxtLogoRaw from '~/assets/nuxt.svg?raw'
Done

2019-10-31 10:49 UTC, ricardogobbosouza approved these changes

2019-11-08 12:23 UTC, preventdefault commented
Exactly that we need, thanks for this PR. :)

2019-11-21 12:25 UTC, bravokiloecho commented
Would it be possible to get this merged sometime soon? Thanks!

2019-11-21 13:50 UTC, brhx approved these changes
Thanks for the PR! 👍

2019-11-21 13:50 UTC, merged

2019-11-21 13:58 UTC, bravokiloecho commented
Awesome, thanks @sam3d! Would you be able to take a look at this one too? https://github.com/nuxt-community/svg-module/pull/20

2019-11-21 14:10 UTC, sam3d commented
No problem! And sure 😊